export const boyName = [ 
    'Aaron','Ahmad','Alex','Andrew', 'Anthony','Arnold','Ashton','Augustus','Austin',
    'Benjamin','Bilal','Bishop','Bobby','Bruno','Boscoe',
    'Cain','Chester','Cheyanne','Chris','Christian','Clement','Cole','Connor',
    'Dante','Derek','Dmitri','Drake','Drew','Dwayne',
    'Easton','Elijah','Elson','Emerson','Emmanuel','Emmet','Enrique','Eugene',
    'Felix','Finn','Flint','Frank','Fred',
    'Gary','Garett','George','Gerald','Glen','Gustavo',
    'Hector','Henry','Hassan',
    'Igor','Isaac',
    'Jaquan','Jason','Jasper','Jackson','Jeremiah','Jermaine','Jonathan','Jordan','Joseph','Joshua','Julian','Julius',
    'Kanye','Karim','Kevin','Kobe','Kyle',
    'Leonard','Lionel','Loas','Logan','Lucas','Luther',
    'Mark','Marvin','Mathias','Maverick','Maxwell','Miguel','Michael','Miles','Mohammad','Murray',
    'Nick', 'Nelson',
    'Omar','Oscar','Oshay','Owen','Otto',
    'Patrick','Payton','Peter','Phil',
    'Qasim', 'Quincy',
    'Rico','Rick','Riley','Ryan',
    'Salim','Samuel','Sean','Sergei','Shane','Shaquille','Skylar','Spencer','Steven',
    'Tony','Trevor','Tristan','Troy','Tyler','Tyson',
    'Ulisses',
    'Victor',
    'Weston','William','Wilson','Winston','Wyatt',
    'Xavier',
    'Yevgeny', 
    'Zachary','Zeke','Zuko'
]

export const girlName = [
    'Abigail','Amanda','Amy','Anna','Ashley','Audrey','Avery',
    'Barbara','Beth','Briana','Britney',
    'Carol','Charlotte','Chester','Colette','Celine','Clementine','Connie','Constance','Corinth',
    'Daphne','Delilah','Donna','Dorothy',
    'Emily','Esther','Evelyn',
    'Farrah','Fiona','Francis',
    'Gloria',
    'Haley','Hannah','Harper','Hayden','Heather',
    'Isabelle','Iman','Ivy',
    'Jacqueline','Jade','Jennifer','Jessie','Joanna','Julia','Juliette',
    'Kahanna','Karen','Kate','Kathy','Katya','Kelly','Kristen',
    'Latrice','Lily','Lydia',
    'Mackenzie','Madison','Masha','Malaysia','Maya','Megan','Mia','Michaela','Moana','Moira','Molly','Monica','Morgan',
    'Naomi','Naysha','Nicole','Nina',
    'Olga','Olive','Olivia',
    'Patricia','Penelope','Phoebe','Priya',
    'Quinn',
    'Rachel','Riley','Rita','Rosetta','Roslyn',
    'Saadia','Sarah','Sasha','Sharon','Shanti','Shauna','Sophia','Stella','Susan',
    'Tasha','Tatianna','Taylor','Tessa','Tiffany','Trixie',
    'Ursula','Ulba',
    'Venus','Vicky','Victory','Volha',
    'Wanda','Wendy','Willow','Wynona',
    'Xena',
    'Yolanda','Yvonne',
    'Zoey',
]

export const lastName = [
    'Adair','Addams','Adler','Agusto','Albani','Allegro','Ali','Alvarez','Anderson','Armstrong','Asai','Ashford','Aubertin',
    'Ballo','Barlowe','Bell','Belsky','Bennett','Benson','Berry','Bertz','Besselman','Bhandari','Bickler','Bidinger','Brown',
    'Cadelle','Carter','Caville','Clarke','Coin','Coleman','Coolidge','Colombus','Cortez','Cortova','Cruise','Cruz',
    'Dawson','Dejardin','Delong','DeNeres','Diaz','Drake','Dupree',
    'Edmonton','Egger','Eli','Elrod',
    'Fauci','Fence','Fletcher','Ferrara','Fester','Finch','Fontaine','Ford','Forrester','Fox','Fugi',
    'Gale','Goode','Gomez','Gonzales','Gosling','Goyer',
    'Hanoman','Heart','Higashi','Hill','Hitchens','Huxley','Huxtable',
    'Innes','Irwin',
    'Jackson','Jefferson','Jones',
    'Kane','Kassis','Keith','Keller','Khoury','Kresley','Kumar',
    'Lamothe','Landry','Langdon','Lewinsky','Lincoln','Lipton','Long','Lopez',
    'Mammen','Markov','Mathai','McKenzie','Mandrake','Messi','Milan','Miller','Montana','Montgomery','Musitz','Mustafa',
    'Nath','Nelson','Nguyen','North',
    'Oakley','Obi','Okeke','Oneal','Orion','Owusu',
    'Palmer','Pandit','Parikh','Paulson','Pete','Pierce','Piers','Powers',
    'Qul','Qureshi',
    'Remmington','Reynolds','Rich','Roberts','Romanoff','Ronaldo',
    'Saaed','Salvador','Segal','Senatra','Shepherd','Shinobi','Short','Singh','Stevens','Streicher','Summer','Sue','Suresh',
    'Taylor','Thatcher','Theodore','Thomas','Toledo','Tolke','Trooper',
    'Uqwu','Uzman',
    'Vasili','Vaughan','Voellinger','Von Eschen', 'Von Feldt','Vox',
    'Washington','Waterman','Watson','Wayans','Weissman','West','White','Williams','Wilson','Wong',
    'Xing',
    'Yamasaki','York',
    'Zaza','Zoeller','Zuckerberg'
]
