export const boyName = [ 
    'Aaron', 'Ahmad','Alex', 'Andrew', 'Anthony', 'Arnold','Austin',
    'Bruno', 'Boscoe',
    'Chris','Christian','Clement','Connor',
    'Dante','Derek','Dmitri','Dwayne',
    'Elijah','Elson','Emmanuel','Emmet','Eugene',
    'Felix','Flint','Frank','Fred',
    'Gary','George','Glen','Gustavo',
    'Hector','Henry',
    'Igor','Isaac',
    'Jaquan','Jason','Jackson','Jeremiah','Jermaine','Jonathan','Jordan','Joshua','Julius',
    'Kevin','Kyle',
    'Leonard','Lionel', 'Luther',
    'Mark','Maxwell','Miguel','Michael','Mohammad',
    'Nick', 'Nelson',
    'Omar','Oscar','Oshay','Owen','Otto',
    'Patrick','Peter',
    'Qasim', 'Quincy',
    'Rico','Rick','Ryan',
    'Salim','Samuel','Sean','Sergei','Shane','Shaquille','Skylar','Steven',
    'Tony','Trevor','Troy',
    'Ulisses',
    'Victor',
    'Weston','William','Wilson','Winston',
    'Xavier',
    'Yevgeny', 
    'Zachary','Zeke'
]

export const girlName = [
    'Abigail','Amanda','Amy','Anna','Ashley','Audrey',
    'Barbara','Beth','Briana','Britney',
    'Carol','Celine','Constance',
    'Delilah','Donna','Dorothy',
    'Emily','Esther',
    'Farrah','Fiona','Francis',
    'Gloria',
    'Hannah','Heather',
    'Isabelle','Iman',
    'Jacqueline','Jennifer','Jessie','Julia','Juliette',
    'Kahanna','Karen','Kate','Kathy','Katya','Kelly','Kristen',
    'Latrice','Lily',
    'Masha','Malaysia','Maya','Moana','Moira',
    'Naomi','Naysha','Nicole',
    'Olga',
    'Phoebe','Priya',
    'Quinn',
    'Rachel','Rita','Rosetta','Roslyn',
    'Sasha','Sharon','Shauna','Sophia','Susan',
    'Tasha','Tatianna','Taylor','Trixie',
    'Ursula','Ulba',
    'Velma','Vicky','Victory','Volha',
    'Wanda','Wendy','Wynona',
    'Xena',
    'Yolanda','Yvonne',
    'Zoey'
]

export const lastName = [
    'Ali','Armstrong',
    'Bell','Benson','Brown',
    'Caville','Clarke','Cortova','Cruise',
    'Dawson','DeNeres','Denton','Dupree',
    'Edmonton','Egger','Eli',
    'Fauci','Fence','Fletcher','Ferrara',
    'Gale','Goode','Gosling',
    'Hanoman','Hill','Hitchens',
    'Innes','Irwin',
    'Jackson','Jefferson','Jones',
    'Kane','Keith','Keller',
    'Langdon','Lipton','Long','Lopez',
    'Montana','Montgomery','Musitz','Mustafa',
    'Nelson','Nguyen','North',
    'Oakley','Obi','Oneal','Orion',
    'Palmer','Paulson','Pete','Powers',
    'Quiet','Qul',
    'Reynolds', 'Rich','Roberts','Ronaldo',
    'Salvador','Senet','Shinobi','Stevens',
    'Summer','Sue',
    'Taylor','Theodore','Thomas','Toledo',
    'Uqwu','Uzman',
    'Vaughan','Vox',
    'Watson','Wayans','West','White','Williams','Wong',
    'Xing',
    'Yamasaki','York',
    'Zaza','Zuckerberg'
]
