export const boyName = [ 
    'Aaron','Abdul','Ahmad','Alex','Alfonzo','Andrew', 'Anthony','Arnold','Arthur','Artie','Ashton','Augustus','Austin',
    'Benjamin','Bilal','Bishop','Bobby','Bruno','Boscoe',
    'Caesar','Cain','Calvin','Chance','Chester','Cheyanne','Chris','Christian','Clement','Cole','Connor','Cory',
    'Danial','Dante','Derek','Derrick','Dmitri','Donald','Donovan','Drake','Drew','Dwayne',
    'Easton','Elijah','Elson','Emerson','Emmanuel','Emmet','Enrique','Esteban','Eugene',
    'Farzin','Felix','Finn','Flint','Frank','Fred',
    'Gary','Garett','Gaston','George','Gerald','Glen','Gunther','Gustavo',
    'Hector','Henry','Hassan',
    'Igor','Isaac','Ivan',
    'Jake','Jaquan','Jason','Jasper','Jackson','Jeremiah','Jermaine','Jonathan','Jordan','Joseph','Joshua','Judas','Julian','Julius',
    'Kanye','Karim','Kevin','Kobe','Kyle',
    'Leonard','Lionel','Loas','Logan','Lucas','Luther',
    'Mark','Marvin','Mathias','Maverick','Maxwell','Miguel','Michael','Miles','Mohammad','Murray',
    'Neal','Nelson','Niall','Nick','Nyle',
    'Omar','Oscar','Oshay','Owen','Otto',
    'Patrick','Payton','Peter','Phil',
    'Qasim', 'Quincy',
    'Rico','Rick','Riley','Ryan',
    'Salim','Samuel','Seamus','Sean','Sergei','Shane','Shaquille','Shaun','Shiloh','Simon','Skylar','Spencer','Steven',
    'Tony','Trevor','Tristan','Troy','Tyler','Tyson',
    'Ulisses',
    'Victor',
    'Walter','Weston','Wilbur','William','Wilson','Winston','Wyatt',
    'Xavier',
    'Yevgeny', 
    'Zachary','Zeke','Zuko'
]

export const girlName = [
    'Abigail','Amanda','Amy','Anabelle','Anetra','Anna','April','Ashley','Audrey','Avery',
    'Barbara','Beth','Briana','Britney',
    'Carol','Charlotte','Chester','Colette','Celine','Chanel','Cherry','Cheryl','Cindy','Clementine','Connie','Constance','Corinth',
    'Daphne','Delilah','Donna','Dorothy',
    'Ellen','Emily','Esther','Eve','Evelyn',
    'Faith','Farrah','Fayette','Fiona','Francis',
    'Gabriella','Genesis','Gertrude','Gina','Gloria',
    'Haley','Hannah','Harper','Hayden','Heather','Helen',
    'Isabelle','Iman','Ivy',
    'Jacqueline','Jade','Jennifer','Jessie','Jillian','Joanna','Julia','Juliette','June',
    'Kahanna','Karen','Kate','Kathy','Katya','Kelly','Konnika','Kristen',
    'Latrice','Leona','Lily','Loni','Lydia','Lynn',
    'Mackenzie','Madison','Maria','Mariah','Mary','Masha','Malaysia','May','Maya','Megan','Mia','Michaela','Mirabelle','Moana','Moira','Molly','Monica','Morgan',
    'Naomi','Naysha','Nicole','Nina',
    'Olga','Olive','Olivia',
    'Pan','Patricia','Penelope','Phoebe','Priya',
    'Quinn',
    'Rachel','Riley','Rita','Rose','Rosetta','Roslyn',
    'Saadia','Samantha','Sarah','Sasha','Selena','Serena','Sharon','Shanti','Shauna','Sidibe','Sonya','Sophia','Stella','Susan',
    'Tanya','Tasha','Tatianna','Taylor','Tessa','Tiffany','Tracy','Trixie','Tyra',
    'Ursula','Ulba',
    'Venus','Vicky','Victory','Volha',
    'Wanda','Wendy','Willow','Wynona',
    'Xena',
    'Yolanda','Yvonne',
    'Zoey',
]

export const lastName = [
    'Adair','Addams','Adler','Agusto','Albani','Allegro','Ali','Alvarez','Anderson','Armstrong','Asai','Ashford','Aubertin',
    'Bailey','Ballo','Barlowe','Bell','Belsky','Bennett','Benson','Bernard','Berry','Bertz','Besselman','Bhandari','Bickler','Bidinger','Boston','Brown',
    'Cadelle','Carter','Caville','Clarke','Coin','Coleman','Coolidge','Colombus','Cortez','Cortova','Cruise','Cruz',
    'Dawson','Dejardin','Delaware','Delong','DeNeres','Diaz','Drake','Dupree',
    'Edmonton','Egger','Eli','Elrod',
    'Farsi','Fauci','Fence','Fletcher','Ferrara','Fester','Finch','Fontaine','Ford','Forrester','Fox','Fugi',
    'Gale','Goode','Gomez','Gonzales','Gosling','Goyer',
    'Hanoman','Heart','Higashi','Hill','Hitchens','Huxley','Huxtable',
    'Innes','Irwin',
    'Jackson','Jefferson','Jones',
    'Kane','Kassis','Keith','Keller','Khoury','Kresley','Kumar',
    'Lamothe','Landry','Langdon','Lewinsky','Lincoln','Lipton','Long','Lopez',
    'Mammen','Markov','Mathai','McKenzie','Mandrake','Messi','Milan','Miller','Milton','Montana','Mosby','Montgomery','Musitz','Mustafa',
    'Naderi','Nath','Nelson','Nguyen','Nichols','North',
    'Oakley','Obi','Okeke','Oneal','Orion','Owusu',
    'Palmer','Pandit','Parikh','Paulson','Pete','Phillis','Pierce','Piers','Powers',
    'Qul','Qureshi',
    'Remmington','Reynolds','Rich','Roberts','Romanoff','Ronaldo',
    'Saaed','Salvador','Segal','Senatra','Shepherd','Shinobi','Short','Simmons','Singh','Sosa','Stark','Stevens','Streicher','Summer','Sue','Suresh',
    'Taylor','Thatcher','Theodore','Thomas','Thompson','Thrombey','Toledo','Tolke','Trooper',
    'Uqwu','Uzman',
    'Vasili','Vaughan','Voellinger','Von Eschen', 'Von Feldt','Vox',
    'Washington','Westberg','Watson','Wayans','Weissman','West','White','Williams','Wilson','Wong',
    'Xing',
    'Yamasaki','York',
    'Zaza','Zoeller','Zuckerman'
]
